services:
  emby:
    container_name: emby
    image: lscr.io/linuxserver/emby:latest
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1000
      - PGID=1000
    ports:
      - 8097:8096
    restart: unless-stopped
    volumes:
      - /home/devdaniel/emby/config:/config
      - /mnt/seagate2tb/Movies:/data/movies
      - /mnt/seagate2tb/Series:/data/tvshows

  jellyfin:
    container_name: jellyfin-server
    image: lscr.io/linuxserver/jellyfin:latest
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1000
      - PGID=1000
    ports:
      - 8096:8096
    restart: unless-stopped
    volumes:
      - /home/devdaniel/jelly/config:/config
      - /mnt/seagate2tb/Movies:/data/movies
      - /mnt/seagate2tb/Series:/data/series
