services:
  nordvpn:
    container_name: nordvpn
    image: bubuntux/nordvpn:latest
    cap_add:
      - NET_ADMIN               # Required
      - NET_RAW                 # Required
    environment:
      - CONNECT=Netherlands
      - TECHNOLOGY=NordLynx
      - NETWORK=10.0.0.0/24
      - TOKEN=*insert nordvpn token*
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
    ports:
      - 7878:7878/tcp # Radarr
      - 8080:8080/tcp # qBittorrent
      - 8191:8191/tcp # Flaresolverr
      - 8787:8787/tcp # Readarr
      - 8989:8989/tcp # Sonarr
      - 9696:9696/tcp # Prowlarr
    restart: always

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    network_mode: service:nordvpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - WEBUI_PORT=9696
    restart: unless-stopped
    volumes:
      - /home/devdaniel/prowlarr/config:/config
    depends_on:
      - nordvpn

  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    network_mode: service:nordvpn
    environment:
      - TZ=Europe/Amsterdam
      - WEBUI_PORT=8191
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
    depends_on:
      - nordvpn

  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent:latest
    network_mode: service:nordvpn
    environment:
      - WEBUI_PORT=8080
      - PUID=1000
      - PGID=1000
    restart: always
    volumes:
      - /home/devdaniel/qbittorrent/config:/config
      - /mnt/seagate2tb/downloads:/downloads
    depends_on:
      - nordvpn

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    network_mode: service:nordvpn
    environment:
      - TZ=Europe/Amsterdam
      - WEBUI_PORT=7878
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
    volumes:
      - /home/devdaniel/radarr/config:/config
      - /mnt/seagate2tb/Movies:/movies
      - /mnt/seagate2tb/downloads:/downloads
    depends_on:
      - nordvpn

  readarr:
    container_name: readarr
    image: lscr.io/linuxserver/readarr:develop
    network_mode: service:nordvpn
    environment:
      - TZ=Europe/Amsterdam
      - WEBUI_PORT=8787
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
    volumes:
      - /home/devdaniel/readarr/config:/config
      - /mnt/seagate2tb/Books:/books
      - /mnt/seagate2tb/downloads:/downloads
    depends_on:
      - nordvpn

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    network_mode: service:nordvpn
    environment:
      - PGID=1000
      - TZ=Europe/Amsterdam
      - WEBUI_PORT=8989
      - PUID=1000
    restart: unless-stopped
    volumes:
      - /home/devdaniel/sonarr/config:/config
      - /mnt/seagate2tb/Series:/tv
      - /mnt/seagate2tb/downloads:/downloads
    depends_on:
      - nordvpn
